flyway:
  enabled: false
  url: jdbc:mysql://127.0.0.1:3306/test
  user: test
  password: 123456
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://databases:3306/test
    username: test
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    serialization:
      indent_output: true